---
title: "Pragmatics in CTSL - Norming for Object Namability"
output: rmarkdown::github_document
#output:
  #html_document: default
  #pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r data import, include=FALSE}
library(tidyverse)
theme_set(theme_bw())

dir <- "../data/csv_files"
participant_files <- list.files(path = dir, full.names = TRUE)
df <- plyr::ldply(participant_files, function(x) {
  read_csv(x)
})
#df <- df %>% mutate_if(is.character, factor)

df$cresponse = gsub("[\\\\]","xx", df$response)
df$cresponse = tolower(gsub("xxn","", df$cresponse))

```

```{r responses, include=FALSE}
responses = df %>%
  filter(str_detect(trial_type,"bot_check", negate = TRUE)) %>%
  group_by(object,cresponse,trial_type,label) %>%
  summarize(count=n()) 

overinformativeness = responses %>% filter(trial_type=="overinformativeness")
adjordering = responses %>% filter(trial_type=="adjective_ordering")
```

```{r overinformativeness, echo=FALSE}
over = overinformativeness %>%
  group_by(object,label) %>%
  summarise() %>%
  mutate(id = row_number()) 

ggplot(overinformativeness, aes(x=cresponse, y=count)) +
  geom_bar(stat="identity",fill="steelblue") +
  facet_wrap(~object, scales="free") +
  #scale_fill_manual(values=c('#999999','#E69F00')) +
  coord_flip() #+
  #scale_x_discrete(guide = guide_axis(n.dodge=3)) +
  theme(legend.position = "none")
  
ggsave(file="../graphs/namability-overinformativeness.pdf",width=30,height=25)
```

```{r adjordering, echo=FALSE}
ggplot(adjordering, aes(x=cresponse, y=count,fill=object)) +
  geom_bar(stat="identity") +
  facet_wrap(~label, scales="free") +
  coord_flip() #+
  #scale_x_discrete(guide = guide_axis(n.dodge=3)) +
  theme(legend.position = "none")
  
ggsave(file="../graphs/namability-adjordering.pdf",width=35,height=20)
```





